apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: 0.18.2
  interval: 10s
  install:
    createNamespace: true
  targetNamespace: kube-system
  values:
    fullnameOverride: sealed-secrets-controller
