apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-distributed
  namespace: kube-logging
spec:
  chart:
    spec:
      chart: loki-distributed
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 0.56.0
  interval: 10s
  install:
    createNamespace: true
  targetNamespace: kube-logging
  valuesFrom:
  - kind: Secret
    name: loki-values
