---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-distributed
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-distributed
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helm-repos
  interval: 30s
  targetNamespace: development

