apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo-distributed
  namespace: kube-trace
spec:
  chart:
    spec:
      chart: tempo-distributed
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 0.24.2
  interval: 10s
  install:
    createNamespace: true
  targetNamespace: kube-trace
