apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo-distributed
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tempo-distributed
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 0.24.2
  interval: 1m0s
  targetNamespace: kube-logging
